In [83]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [84]:
df = pd.read_csv("dataset/cgpa_marks_package.csv")
df

cgpa  Interview_marks  package
0    6.89               26     3.26
1    5.12               38     1.98
2    7.82               40     3.25
3    7.42                8     3.67
4    6.94               17     3.57
..    ...              ...      ...
195  6.93               44     2.46
196  5.89               34     2.57
197  7.21               27     3.24
198  7.63               44     3.96
199  6.22               25     2.33

[200 rows x 3 columns]

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   cgpa             200 non-null    float64
 1   Interview_marks  200 non-null    int64  
 2   package          200 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 4.8 KB


In [86]:
from sklearn.model_selection import train_test_split

In [87]:
x=df[["cgpa","Interview_marks"]]
x

cgpa  Interview_marks
0    6.89               26
1    5.12               38
2    7.82               40
3    7.42                8
4    6.94               17
..    ...              ...
195  6.93               44
196  5.89               34
197  7.21               27
198  7.63               44
199  6.22               25

[200 rows x 2 columns]

In [88]:
y=df[["package"]]
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [89]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [90]:
from sklearn.linear_model import LinearRegression

In [91]:
lr=LinearRegression()

In [92]:
lr.fit(x_train,y_train)

LinearRegression()

In [93]:
A=lr.predict(x_test)
A

array([[3.89979454],
       [3.10237603],
       [2.36034882],
       [2.57822923],
       [1.66423151],
       [1.77914693],
       [2.08134881],
       [2.92901527],
       [3.7593373 ],
       [2.94790193],
       [4.09998866],
       [3.49398191],
       [2.97359571],
       [2.39870713],
       [3.19384646],
       [3.4621268 ],
       [1.93146344],
       [3.25681974],
       [2.9880456 ],
       [3.41027583],
       [2.56926451],
       [3.151021  ],
       [2.87038758],
       [3.08699931],
       [3.69790624],
       [2.86102024],
       [3.50664644],
       [3.34610218],
       [3.91270221],
       [1.95041088],
       [3.64670105],
       [3.1989594 ],
       [3.70541992],
       [2.79068524],
       [2.79176404],
       [3.27804635],
       [3.53178562],
       [2.61449072],
       [2.6652021 ],
       [2.71320129]])

In [94]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,A)

0.2873891848877421

In [95]:
from sklearn.metrics import r2_score
r2_score(y_test,A)

0.7805012233012033

In [96]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,A)
mse

0.12141898593789571

In [97]:
np.sqrt(mse)

0.34845227210895857

In [98]:
lr.coef_

array([[ 5.57635318e-01, -5.54595982e-04]])

In [99]:
lr.intercept_

array([-0.87639755])