# Pandas Series

In [4]:
import numpy as np
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)
a=pd.Series(['a','b','c','d','e'])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [5]:
import numpy as np
import pandas as pd
score=pd.Series([23,45,65,43,10,15,21,37,9,4,11])
print(score)


0     23
1     45
2     65
3     43
4     10
5     15
6     21
7     37
8      9
9      4
10    11
dtype: int64


In [6]:
import numpy as np
import pandas as pd
i=pd.Index(['Rohit','Rahul','Virat','Sky','DK','Axar','Hardik','Ashwin','Arshdeep','Chahal','Kumar'])
score=pd.Series([23,45,65,43,10,15,21,37,9,4,11],index=i)
print(score)


Rohit       23
Rahul       45
Virat       65
Sky         43
DK          10
Axar        15
Hardik      21
Ashwin      37
Arshdeep     9
Chahal       4
Kumar       11
dtype: int64


# DataFrames:

In [4]:
import numpy as np
import pandas as pd
arr=np.arange(0,9).reshape(3,3)
print(arr)    #Numpy ndarray
df=pd.DataFrame(arr,index=['a','b','c'],columns=['A','B','C'])
print(df)     #Pandas data frame


[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [5]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[23,24,20,19],[20,24,25,21],[19,22,23,18]], index=['Rahul','Krishna','Abhinav'], columns=['OSA','Python','SE','Java'])
print(df)

         OSA  Python  SE  Java
Rahul     23      24  20    19
Krishna   20      24  25    21
Abhinav   19      22  23    18


In [6]:
import numpy as np
import pandas as pd
ser1=pd.Series([23,20,19])
ser2=pd.Series([20,23,25,20])
print(pd.DataFrame({"OSA":ser1,"Python":ser2}))

    OSA  Python
0  23.0      20
1  20.0      23
2  19.0      25
3   NaN      20


# Create DataFrame containing Infotmation about cities

In [8]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
#print(i)
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Population")
#print(pop)
cap=pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i, name="Capital")
#print(cap)
#df=pd.DataFrame ([pop,cap])     #will not display in proper format
#df=pd.DataFrame ([pop,cap]).T   #will Display in proper format but columns names missing
df=pd.DataFrame({"Population":pop, "Capital":cap})
#df=pd.DataFrame([['6.72','Bangalore'],[.12.54,'Mumbai'],['7.0','Gandhinagar']],index=["Karnataka",'Maharashtra',''Gandhinagar],columns=['Population','Capital'])#creating dataframe in one line
print(df)

            Population      Capital
Karnataka         6.72    Bangalore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar


# How to Add new Data to series

In [10]:
import numpy as np
import pandas as pd
#print(pop)
pop.append(pd.Series({"TamilNadu":8.9}))
#print(pop)

# How to Add new Data to series

C:\Users\CS-L2-PC05\AppData\Local\Temp\ipykernel_6448\2480367972.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"TamilNadu":8.9}))


Karnataka       6.72
Maharashtra    12.54
Gujarat          7.0
TamilNadu        8.9
dtype: object

# How to Add new Data to series

Method 1

In [11]:
import numpy as np
import pandas as pd
df=pd.DataFrame([['6.72','Bangalore'],['12.54;','Mumbai'],['7.0','Gandhinagar']],index=['Karnataka','Maharashtra','Gujarat'],columns=['Population','Capital'])
#print(df)
print(df.append(pd.DataFrame([['8.9','Chennai'],['12.54','Hyderabad']],index=['TamilNadu','Andhra Pradesh'],columns=['Population','Capital'])))


               Population      Capital
Karnataka            6.72    Bangalore
Maharashtra        12.54;       Mumbai
Gujarat               7.0  Gandhinagar
TamilNadu             8.9      Chennai
Andhra Pradesh      12.54    Hyderabad


C:\Users\CS-L2-PC05\AppData\Local\Temp\ipykernel_6448\2173967018.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([['8.9','Chennai'],['12.54','Hyderabad']],index=['TamilNadu','Andhra Pradesh'],columns=['Population','Capital'])))


Method 2

In [12]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Capital")
cap=pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i, name="Capital")
df=pd.DataFrame({"Population":pop,"Capital":cap})
print(df)
print(df.append(pd.DataFrame({"Population":pd.Series({"TamilNadu":8.9,"Andhra Pradesh":12.6}),"Capital":pd.Series({"TamilNadu":"Chennai","Andhra Pradesh":"Hyderabad"})})))

            Population      Capital
Karnataka         6.72    Bangalore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar
               Population      Capital
Karnataka            6.72    Bangalore
Maharashtra         12.54       Mumbai
Gujarat               7.0  Gandhinagar
TamilNadu             8.9      Chennai
Andhra Pradesh       12.6    Hyderabad


C:\Users\CS-L2-PC05\AppData\Local\Temp\ipykernel_6448\455407473.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"Population":pd.Series({"TamilNadu":8.9,"Andhra Pradesh":12.6}),"Capital":pd.Series({"TamilNadu":"Chennai","Andhra Pradesh":"Hyderabad"})})))


# Concat new column to Dataframe

In [3]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.8'],index=i,name='Population')
cap=pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i,name='Capital')
df=pd.DataFrame({'Population':pop,'Capital':cap})
#print(df)
df1=pd.concat(
        [df,pd.DataFrame({
                            "Area":pd.Series(['2.1','3.1','5.5'],index=pop.index),
                            "CM":pd.Series(['Bomai','Shinde','XYZ'],index=pop.index)
                        })
        ],axis=1
    )
df1.to_csv('cities.csv')
print(df1)

            Population      Capital Area      CM
Karnataka         6.72    Bangalore  2.1   Bomai
Maharashtra      12.54       Mumbai  3.1  Shinde
Gujarat            7.8  Gandhinagar  5.5     XYZ


# Subsetting

In [8]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [9]:
srs = Series(np.arange(5), index=["alpha","beta","gama","delta","elipson"])
srs

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32

In [10]:
srs[:2]

alpha    0
beta     1
dtype: int32

In [11]:
srs[["beta","delta"]]

beta     1
delta    3
dtype: int32

In [12]:
srs["beta":"delta"]

beta     1
gama     2
delta    3
dtype: int32

In [13]:
print(srs)
srs[srs > 3]

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32


elipson    4
dtype: int32

In [14]:
srs > 3

alpha      False
beta       False
gama       False
delta      False
elipson     True
dtype: bool

In [15]:
srs2 = Series(["zero","one","two","three","four"], index=[3,2,4,0,1])
srs2

3     zero
2      one
4      two
0    three
1     four
dtype: object

In [16]:
srs2[2:4]    #Ambiguous

4      two
0    three
dtype: object

In [17]:
srs2.iloc[1:4]

2      one
4      two
0    three
dtype: object

In [18]:
srs2.loc[3:0]

3     zero
2      one
4      two
0    three
dtype: object

In [19]:
df = DataFrame(np.arange(21).reshape(7,3), columns=['AAA','BBB','CCC'], index=["alpha","beta","gama","delta","epsilon","zeta","eta"])
df

AAA  BBB  CCC
alpha      0    1    2
beta       3    4    5
gama       6    7    8
delta      9   10   11
epsilon   12   13   14
zeta      15   16   17
eta       18   19   20

In [20]:
df.AAA

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [21]:
df['AAA']

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [22]:
df[['BBB','CCC']]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [23]:
df.iloc[1:3, 1:2]

BBB
beta    4
gama    7

In [24]:
df.loc['beta':'delta', 'BBB':'CCC']

BBB  CCC
beta     4    5
gama     7    8
delta   10   11

In [25]:
df.iloc[:, 1:3]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [26]:
df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']]

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [27]:
df2 = df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']].copy()
df2

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [28]:
df2['CCC'] = Series({'alpha':11, 'gama':18, 'zeta':5})
df2

BBB  CCC
alpha    1   11
gama     7   18
zeta    16    5

In [29]:
df2.iloc[1, 1] = 2
df2

BBB  CCC
alpha    1   11
gama     7    2
zeta    16    5

In [30]:
df2.iloc[:, 1] = 0
df2

BBB  CCC
alpha    1    0
gama     7    0
zeta    16    0