# Pandas Series

In [4]:
import numpy as np
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)
a=pd.Series(['a','b','c','d','e'])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [5]:
import numpy as np
import pandas as pd
score=pd.Series([23,45,65,43,10,15,21,37,9,4,11])
print(score)


0     23
1     45
2     65
3     43
4     10
5     15
6     21
7     37
8      9
9      4
10    11
dtype: int64


In [6]:
import numpy as np
import pandas as pd
i=pd.Index(['Rohit','Rahul','Virat','Sky','DK','Axar','Hardik','Ashwin','Arshdeep','Chahal','Kumar'])
score=pd.Series([23,45,65,43,10,15,21,37,9,4,11],index=i)
print(score)


Rohit       23
Rahul       45
Virat       65
Sky         43
DK          10
Axar        15
Hardik      21
Ashwin      37
Arshdeep     9
Chahal       4
Kumar       11
dtype: int64


# DataFrames:

In [4]:
import numpy as np
import pandas as pd
arr=np.arange(0,9).reshape(3,3)
print(arr)    #Numpy ndarray
df=pd.DataFrame(arr,index=['a','b','c'],columns=['A','B','C'])
print(df)     #Pandas data frame


[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [5]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[23,24,20,19],[20,24,25,21],[19,22,23,18]], index=['Rahul','Krishna','Abhinav'], columns=['OSA','Python','SE','Java'])
print(df)

         OSA  Python  SE  Java
Rahul     23      24  20    19
Krishna   20      24  25    21
Abhinav   19      22  23    18


In [6]:
import numpy as np
import pandas as pd
ser1=pd.Series([23,20,19])
ser2=pd.Series([20,23,25,20])
print(pd.DataFrame({"OSA":ser1,"Python":ser2}))

    OSA  Python
0  23.0      20
1  20.0      23
2  19.0      25
3   NaN      20


# Create DataFrame containing Infotmation about cities

In [8]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
#print(i)
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Population")
#print(pop)
cap=pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i, name="Capital")
#print(cap)
#df=pd.DataFrame ([pop,cap])     #will not display in proper format
#df=pd.DataFrame ([pop,cap]).T   #will Display in proper format but columns names missing
df=pd.DataFrame({"Population":pop, "Capital":cap})
#df=pd.DataFrame([['6.72','Bangalore'],[.12.54,'Mumbai'],['7.0','Gandhinagar']],index=["Karnataka",'Maharashtra',''Gandhinagar],columns=['Population','Capital'])#creating dataframe in one line
print(df)

            Population      Capital
Karnataka         6.72    Bangalore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar


# How to Add new Data to series

In [10]:
import numpy as np
import pandas as pd
#print(pop)
pop.append(pd.Series({"TamilNadu":8.9}))
#print(pop)

# How to Add new Data to series

C:\Users\CS-L2-PC05\AppData\Local\Temp\ipykernel_6448\2480367972.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"TamilNadu":8.9}))


Karnataka       6.72
Maharashtra    12.54
Gujarat          7.0
TamilNadu        8.9
dtype: object

# How to Add new Data to series

Method 1

In [11]:
import numpy as np
import pandas as pd
df=pd.DataFrame([['6.72','Bangalore'],['12.54;','Mumbai'],['7.0','Gandhinagar']],index=['Karnataka','Maharashtra','Gujarat'],columns=['Population','Capital'])
#print(df)
print(df.append(pd.DataFrame([['8.9','Chennai'],['12.54','Hyderabad']],index=['TamilNadu','Andhra Pradesh'],columns=['Population','Capital'])))


               Population      Capital
Karnataka            6.72    Bangalore
Maharashtra        12.54;       Mumbai
Gujarat               7.0  Gandhinagar
TamilNadu             8.9      Chennai
Andhra Pradesh      12.54    Hyderabad


C:\Users\CS-L2-PC05\AppData\Local\Temp\ipykernel_6448\2173967018.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([['8.9','Chennai'],['12.54','Hyderabad']],index=['TamilNadu','Andhra Pradesh'],columns=['Population','Capital'])))


Method 2

In [12]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Capital")
cap=pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i, name="Capital")
df=pd.DataFrame({"Population":pop,"Capital":cap})
print(df)
print(df.append(pd.DataFrame({"Population":pd.Series({"TamilNadu":8.9,"Andhra Pradesh":12.6}),"Capital":pd.Series({"TamilNadu":"Chennai","Andhra Pradesh":"Hyderabad"})})))

            Population      Capital
Karnataka         6.72    Bangalore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar
               Population      Capital
Karnataka            6.72    Bangalore
Maharashtra         12.54       Mumbai
Gujarat               7.0  Gandhinagar
TamilNadu             8.9      Chennai
Andhra Pradesh       12.6    Hyderabad


C:\Users\CS-L2-PC05\AppData\Local\Temp\ipykernel_6448\455407473.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"Population":pd.Series({"TamilNadu":8.9,"Andhra Pradesh":12.6}),"Capital":pd.Series({"TamilNadu":"Chennai","Andhra Pradesh":"Hyderabad"})})))
